[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "abxrcli"
version = "1.0.1"
description = "ArborXR CLI"
readme = "README.md"
authors = [{ name = "Brian Rice", email = "brian@arborxr.com" }]

dependencies = [
    "setuptools",
    "requests",
    "tqdm",
    "pyyaml"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-mock"
]

[project.scripts]
abxr-cli = "abxr.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
